### ISSUE TITLE
Separate post body

### ISSUE THREAD

**Issue by FelixSFD** [SOBotics/Guttenberg#28]
The body of each post should be separated into "plaintext", "blockquote" and "code".

If this is done, the Jaro-Winkler distance should not be calculated for two full posts, but for each of those parts. The values could be combined in one final score like this:

```
(score_plaintext*0.7)+(score_blockquote*0.5)+(score_code*1)
```

**Comment by sbaltes** [comment]
In a recent [research paper](http://empirical-software.engineering/assets/pdf/msr18-sotorrent.pdf), we evaluated different string similarity metrics to match Stack Overflow code and text blocks to their predecessors. Those results could also be interesting for your projects, because our implementations of the metrics are [available on GitHub](https://github.com/sotorrent/string-similarity). You could, for example, use the [Winnowing algorithm](https://theory.stanford.edu/~aiken/publications/papers/sigmod03.pdf) to compare code blocks.
